version: 2.1
jobs:
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install AWS CLI & Ansible
          command: |
            pip install --user awscli ansible
      - run:
          name: Get EC2 public IP
          command: |
            export PUBLIC_IP=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=backend-c00be52" "Name=instance-state-name,Values=running" \
              --region eu-north-1 \
              --query "Reservations[].Instances[].PublicIpAddress" \
              --output text)
            echo "Public IP: $PUBLIC_IP"
      # Add your Ansible deployment command here, using $PUBLIC_IP
workflows:
  version: 2
  deploy:
    jobs:
      - deploy